CREATE TABLE "characters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "characters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"aliases" text[],
	"species" varchar(100) DEFAULT 'Human',
	"status" varchar(50) DEFAULT 'Alive',
	"debut_season_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "characters_to_elements" (
	"character_id" integer NOT NULL,
	"element_id" integer NOT NULL,
	"is_active" boolean DEFAULT true,
	CONSTRAINT "characters_to_elements_character_id_element_id_pk" PRIMARY KEY("character_id","element_id")
);
--> statement-breakpoint
CREATE TABLE "characters_to_seasons" (
	"character_id" integer NOT NULL,
	"season_id" integer NOT NULL,
	CONSTRAINT "characters_to_seasons_character_id_season_id_pk" PRIMARY KEY("character_id","season_id")
);
--> statement-breakpoint
CREATE TABLE "characters_to_weapons" (
	"character_id" integer NOT NULL,
	"weapon_id" integer NOT NULL,
	CONSTRAINT "characters_to_weapons_character_id_weapon_id_pk" PRIMARY KEY("character_id","weapon_id")
);
--> statement-breakpoint
CREATE TABLE "elements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "elements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "elements_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "locations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"realm_id" integer,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "locations_to_seasons" (
	"location_id" integer NOT NULL,
	"season_id" integer NOT NULL,
	CONSTRAINT "locations_to_seasons_location_id_season_id_pk" PRIMARY KEY("location_id","season_id")
);
--> statement-breakpoint
CREATE TABLE "realms" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "realms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "realms_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "seasons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"number" integer,
	"type" varchar(50) DEFAULT 'standard' NOT NULL,
	"title" varchar(255) NOT NULL,
	"episodes_count" integer NOT NULL,
	"release_year" integer,
	"main_antagonist" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "weapons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "weapons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"type" varchar(100) NOT NULL,
	"is_artifact" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "weapons_to_seasons" (
	"weapon_id" integer NOT NULL,
	"season_id" integer NOT NULL,
	CONSTRAINT "weapons_to_seasons_weapon_id_season_id_pk" PRIMARY KEY("weapon_id","season_id")
);
--> statement-breakpoint
ALTER TABLE "characters" ADD CONSTRAINT "characters_debut_season_id_seasons_id_fk" FOREIGN KEY ("debut_season_id") REFERENCES "public"."seasons"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "characters_to_elements" ADD CONSTRAINT "characters_to_elements_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "characters_to_elements" ADD CONSTRAINT "characters_to_elements_element_id_elements_id_fk" FOREIGN KEY ("element_id") REFERENCES "public"."elements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "characters_to_seasons" ADD CONSTRAINT "characters_to_seasons_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "characters_to_seasons" ADD CONSTRAINT "characters_to_seasons_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "characters_to_weapons" ADD CONSTRAINT "characters_to_weapons_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "characters_to_weapons" ADD CONSTRAINT "characters_to_weapons_weapon_id_weapons_id_fk" FOREIGN KEY ("weapon_id") REFERENCES "public"."weapons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_realm_id_realms_id_fk" FOREIGN KEY ("realm_id") REFERENCES "public"."realms"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "locations_to_seasons" ADD CONSTRAINT "locations_to_seasons_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "locations_to_seasons" ADD CONSTRAINT "locations_to_seasons_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weapons_to_seasons" ADD CONSTRAINT "weapons_to_seasons_weapon_id_weapons_id_fk" FOREIGN KEY ("weapon_id") REFERENCES "public"."weapons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weapons_to_seasons" ADD CONSTRAINT "weapons_to_seasons_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "characters_name_idx" ON "characters" USING btree ("name");--> statement-breakpoint
CREATE INDEX "locations_name_idx" ON "locations" USING btree ("name");--> statement-breakpoint
CREATE INDEX "locations_realm_id_idx" ON "locations" USING btree ("realm_id");--> statement-breakpoint
CREATE INDEX "seasons_number_idx" ON "seasons" USING btree ("number");--> statement-breakpoint
CREATE INDEX "weapons_name_idx" ON "weapons" USING btree ("name");